## Step 1: Importing Required Libraries

In [1]:
import pandas as pd
import numpy as np

print("Libraries imported")

Libraries imported

## Step 2: Loading the Datasets

In [2]:
poverty_df = pd.read_csv("../data/poverty.csv")
inflation_df = pd.read_csv("../data/inflation.csv")

print("Datasets imported successfully")

Datasets imported successfully

## Step 3: Initial Dataset Inspection

In [3]:
print("Poverty: ", poverty_df.shape)
print("Inflation: ", poverty_df.shape)

Poverty:  (185, 102)
Inflation:  (185, 102)

### 3.1 Viewing the Datasets

In [5]:
display(poverty_df.head())

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,XKX,WB_WDI_SI_POV_UMIC,_T,_T,_T,PT_POP,...,53.4,49.5,54.7,38.3,38.9,47.0,38.2,NaN,NaN,NaN
1,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,MOZ,WB_WDI_SI_POV_UMIC,_T,_T,_T,PT_POP,...,NaN,NaN,NaN,96.5,NaN,NaN,96.3,NaN,NaN,NaN
2,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,EAS,WB_WDI_SI_POV_UMIC,_T,_T,_T,PT_POP,...,40.7,38.7,35.8,33.5,34.1,29.2,29.6,27.6,26.4,NaN
3,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,GMB,WB_WDI_SI_POV_UMIC,_T,_T,_T,PT_POP,...,NaN,NaN,NaN,NaN,78.2,NaN,NaN,NaN,NaN,NaN
4,datastructure,WB.DATA360:DS_DATA360(1.3),I,A,TUN,WB_WDI_SI_POV_UMIC,_T,_T,_T,PT_POP,...,NaN,NaN,NaN,NaN,NaN,20.7,NaN,NaN,NaN,NaN

In [6]:
display(inflation_df.head())

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,DATABASE_ID,DATABASE_ID_LABEL,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
0,A,Annual,ABW,Aruba,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",PC,Percentage change,IMF_WEO,World Economic Outlook (WEO),...,-1.313,0.744,5.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,Annual,ABW,Aruba,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",PC,Percentage change,IMF_WEO,World Economic Outlook (WEO),...,NaN,NaN,NaN,3.366,2.345,1.815,1.914,1.998,1.998,1.998
2,A,Annual,AFG,Afghanistan,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",PC,Percentage change,IMF_WEO,World Economic Outlook (WEO),...,5.607,7.762,10.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A,Annual,AGO,Angola,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",PC,Percentage change,IMF_WEO,World Economic Outlook (WEO),...,22.277,25.765,21.36,13.639,NaN,NaN,NaN,NaN,NaN,NaN
4,A,Annual,AGO,Angola,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",PC,Percentage change,IMF_WEO,World Economic Outlook (WEO),...,NaN,NaN,NaN,NaN,22.004,12.818,8.506,7.442,7.442,7.442

### 3.2 Examining Dataset Structure

In [7]:
print("POVERTY COLUMNS >>:")
print(poverty_df.columns.tolist())
print("\n")
print("INFLATION COLUMNS >>:")
print(inflation_df.columns.tolist())

POVERTY COLUMNS >>:
['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR', 'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1', 'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'AGG_METHOD', 'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT', 'UNIT_MULT', 'OBS_STATUS', 'OBS_CONF', 'FREQ_LABEL', 'REF_AREA_LABEL', 'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL', 'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL', 'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL', 'UNIT_TYPE_LABEL', 'DECIMALS_LABEL', 'DATABASE_ID_LABEL', 'TIME_FORMAT_LABEL', 'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL', 'OBS_CONF_LABEL', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']


INFLATION COLUMNS >>:
['FREQ', 'FREQ_LABEL', 'REF_AREA', 'REF_AREA_LABEL', 'INDICATOR', 'INDICATOR_LABEL', 'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT', 'UNIT_MULT_LABEL', 'OBS_STATUS', 'OBS_STATUS_LABEL', 'OBS_CONF', 'OBS_CONF_LABEL', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', '2027', '2028', '2029']

### 3.3 Looking at Data Types

In [8]:
print("POVERTY DATASET INFORMATION")
poverty_df.info()

print("\n" + "=" * 40)

print("INFLATION DATASET INFORMATION")
inflation_df.info()

POVERTY DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Columns: 102 entries, STRUCTURE to 2025
dtypes: float64(63), int64(2), object(37)
memory usage: 147.6+ KB

========================================
INFLATION DATASET INFORMATION
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387 entries, 0 to 386
Data columns (total 66 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   FREQ                387 non-null    object
 1   FREQ_LABEL          387 non-null    object
 2   REF_AREA            387 non-null    object
 3   REF_AREA_LABEL      387 non-null    object
 4   INDICATOR           387 non-null    object
 5   INDICATOR_LABEL     387 non-null    object
 6   UNIT_MEASURE        387 non-null    object
 7   UNIT_MEASURE_LABEL  387 non-null    object
 8   DATABASE_ID         387 non-null    object
 9   DATABASE_ID_LABEL   387 non-null    object
 10  UNIT_MULT           387 non-null    int64
 11  UNIT_MULT_LABEL     387 non-null    object
 12  OBS_STATUS          387 non-null    object
 13  OBS_STATUS_LABEL    387 non-null    object
 14  OBS_CONF            387 non-null    object
 15  OBS_CONF_LABEL      387 non-null    object
 16  1980                137 non-null    float64
 17  1981                143 non-null    float64
 18  1982                144 non-null    float64
 19  1983                144 non-null    float64
 20  1984                144 non-null    float64
 21  1985                144 non-null    float64
 22  1986                143 non-null    float64
 23  1987                146 non-null    float64
 24  1988                146 non-null    float64
 25  1989                146 non-null    float64
 26  1990                147 non-null    float64
 27  1991                151 non-null    float64
 28  1992                152 non-null    float64
 29  1993                168 non-null    float64
 30  1994                170 non-null    float64
 31  1995                170 non-null    float64
 32  1996                174 non-null    float64
 33  1997                177 non-null    float64
 34  1998                180 non-null    float64
 35  1999                181 non-null    float64
 36  2000                182 non-null    float64
 37  2001                186 non-null    float64
 38  2002                188 non-null    float64
 39  2003                190 non-null    float64
 40  2004                191 non-null    float64
 41  2005                193 non-null    float64
 42  2006                193 non-null    float64
 43  2007                193 non-null    float64
 44  2008                193 non-null    float64
 45  2009                193 non-null    float64
 46  2010                193 non-null    float64
 47  2011                192 non-null    float64
 48  2012                193 non-null    float64
 49  2013                194 non-null    float64
 50  2014                194 non-null    float64
 51  2015                194 non-null    float64
 52  2016                194 non-null    float64
 53  2017                195 non-null    float64
 54  2018                195 non-null    float64
 55  2019                195 non-null    float64
 56  2020                194 non-null    float64
 57  2021                194 non-null    float64
 58  2022                194 non-null    float64
 59  2023                191 non-null    float64
 60  2024                190 non-null    float64
 61  2025                190 non-null    float64
 62  2026                189 non-null    float64
 63  2027                189 non-null    float64
 64  2028                189 non-null    float64
 65  2029                189 non-null    float64
dtypes: float64(50), int64(1), object(15)
memory usage: 199.7+ KB

## Step 4: Selecting South African Data before cleaning
(We are doing this because we want to ensure that the dataset contains South Africa before cleaning the data)

In [9]:
poverty_sa = poverty_df.loc[
    poverty_df["REF_AREA"] == "ZAF"
].copy()

inflation_sa = inflation_df.loc[
    inflation_df["REF_AREA"] == "ZAF"
].copy()

print(f"South African poverty records: {len(poverty_sa)}")
print(f"South African inflation records: {len(inflation_sa)}")

South African poverty records: 1
South African inflation records: 2

### 4.1 Verifying the Country Selection

In [10]:
print("Poverty country:", poverty_sa["REF_AREA_LABEL"].unique())
print("Inflation country:", inflation_sa["REF_AREA_LABEL"].unique())

assert poverty_sa["REF_AREA"].nunique() == 1
assert inflation_sa["REF_AREA"].nunique() == 1

assert poverty_sa["REF_AREA"].iloc[0] == "ZAF"
assert inflation_sa["REF_AREA"].iloc[0] == "ZAF"

print("\nValidation passed: both datasets contain South Africa (ZAF) only.")

Poverty country: ['South Africa']
Inflation country: ['South Africa']

Validation passed: both datasets contain South Africa (ZAF) only.

## Step 5: Checking for Missing values

In [11]:
print("POVERTY - Missing Values")
print(poverty_sa.isnull().sum())

print("\nINFLATION - Missing Values")
print(inflation_sa.isnull().sum())

POVERTY - Missing Values
STRUCTURE       0
STRUCTURE_ID    0
ACTION          0
FREQ            0
REF_AREA        0
               ..
2021            1
2022            0
2023            1
2024            1
2025            1
Length: 102, dtype: int64

INFLATION - Missing Values
FREQ              0
FREQ_LABEL        0
REF_AREA          0
REF_AREA_LABEL    0
INDICATOR         0
                 ..
2025              1
2026              1
2027              1
2028              1
2029              1
Length: 66, dtype: int64

### Step 5.1: Identifying Missing values and duplicate records

In [12]:
print("POVERTY DATASET")
print("Total missing values:", poverty_sa.isna().sum().sum())
print("Duplicate rows:", poverty_sa.duplicated().sum())

print("\nINFLATION DATASET")
print("Total missing values:", inflation_sa.isna().sum().sum())
print("Duplicate rows:", inflation_sa.duplicated().sum())

POVERTY DATASET
Total missing values: 56
Duplicate rows: 0

INFLATION DATASET
Total missing values: 50
Duplicate rows: 0

### 5.2 Checking Observation Status

In [13]:
print("Poverty observation status:")
print(poverty_sa[["OBS_STATUS", "OBS_STATUS_LABEL"]].drop_duplicates())

print("\nInflation observation status:")
print(
    inflation_sa[["OBS_STATUS", "OBS_STATUS_LABEL"]]
    .drop_duplicates()
)

Poverty observation status:
   OBS_STATUS OBS_STATUS_LABEL
62          A     Normal value

Inflation observation status:
    OBS_STATUS OBS_STATUS_LABEL
381          A     Normal value
382          F   Forecast value

### 5.3 Separating Historical and Forecast Inflation Data

In [14]:
inflation_actual = inflation_sa[
    inflation_sa["OBS_STATUS"] == "A"
].copy()

inflation_forecast = inflation_sa[
    inflation_sa["OBS_STATUS"] == "F"
].copy()

print("Historical inflation records:", len(inflation_actual))
print("Forecast inflation records:", len(inflation_forecast))

Historical inflation records: 1
Forecast inflation records: 1

### 5.4 Checking the Available Time Period

In [15]:
poverty_years = [
    col for col in poverty_sa.columns
    if str(col).isdigit()
]

inflation_years = [
    col for col in inflation_actual.columns
    if str(col).isdigit()
]

print("Poverty period:")
print(min(map(int, poverty_years)), "to", max(map(int, poverty_years)))

print("\nInflation historical period:")
print(
    min(map(int, inflation_years)),
    "to",
    max(map(int, inflation_years))
)

Poverty period:
1963 to 2025

Inflation historical period:
1980 to 2029

In [16]:
print("=" * 50)
print("DUPLICATE RECORDS CHECK")
print("=" * 50)

print(f"\nPOVERTY DATASET:")
print(f"  Total rows: {len(poverty_sa)}")
print(f"  Duplicate rows: {poverty_sa.duplicated().sum()}")

print(f"\nINFLATION DATASET:")
print(f"  Total rows: {len(inflation_sa)}")
print(f"  Duplicate rows: {inflation_sa.duplicated().sum()}")

print("\n No duplicate records found in either dataset.")
print("Data is clean and ready for reshaping.")

==================================================
DUPLICATE RECORDS CHECK
==================================================

POVERTY DATASET:
  Total rows: 1
  Duplicate rows: 0

INFLATION DATASET:
  Total rows: 2
  Duplicate rows: 0

 No duplicate records found in either dataset.
Data is clean and ready for reshaping.

## Step 7: Reshape the Poverty Dataset
We need long format so that the year becomes a row(this will make merging and analysis easier)

In [17]:
poverty_year_columns = [
    col for col in poverty_sa.columns
    if str(col).isdigit() and 1900 <= int(col) <= 2025
]

poverty_long = poverty_sa.melt(
    id_vars=[
        "REF_AREA",
        "REF_AREA_LABEL",
        "INDICATOR",
        "INDICATOR_LABEL"
    ],
    value_vars=poverty_year_columns,
    var_name="Year",
    value_name="Poverty"
)

poverty_long["Year"] = pd.to_numeric(
    poverty_long["Year"],
    errors="coerce"
)

poverty_long["Poverty"] = pd.to_numeric(
    poverty_long["Poverty"],
    errors="coerce"
)

print("Poverty data reshaped successfully.")
display(poverty_long.head())

Poverty data reshaped successfully.

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,Year,Poverty
0,ZAF,South Africa,WB_WDI_SI_POV_UMIC,Poverty headcount ratio at $6.85 a day (2017 P...,1963,NaN
1,ZAF,South Africa,WB_WDI_SI_POV_UMIC,Poverty headcount ratio at $6.85 a day (2017 P...,1964,NaN
2,ZAF,South Africa,WB_WDI_SI_POV_UMIC,Poverty headcount ratio at $6.85 a day (2017 P...,1965,NaN
3,ZAF,South Africa,WB_WDI_SI_POV_UMIC,Poverty headcount ratio at $6.85 a day (2017 P...,1966,NaN
4,ZAF,South Africa,WB_WDI_SI_POV_UMIC,Poverty headcount ratio at $6.85 a day (2017 P...,1967,NaN

### 7.2 Checking Missing Poverty Observations

In [18]:
poverty_missing = poverty_long["Poverty"].isna().sum()
poverty_total = len(poverty_long)

print("Total poverty observations:", poverty_total)
print("Missing poverty observations:", poverty_missing)
print(
    "Missing percentage:",
    round((poverty_missing / poverty_total) * 100, 2),
    "%"
)

Total poverty observations: 63
Missing poverty observations: 56
Missing percentage: 88.89 %

### 7.3 Handling Missing Poverty Observations

In [19]:
poverty_clean = poverty_long.dropna(
    subset=["Year", "Poverty"]
).copy()

print("Observations before cleaning:", len(poverty_long))
print("Observations after cleaning:", len(poverty_clean))
print(
    "Observations removed:",
    len(poverty_long) - len(poverty_clean)
)

Observations before cleaning: 63
Observations after cleaning: 7
Observations removed: 56

### 7.3.1 Justification for Cleaning Decisions

**Why we excluded missing poverty years:**
- Poverty statistics are collected via occasional household surveys, not annually.
- There are only 7 valid observations from 1993 to 2022
- Each survey provides is an independent measurement
- Filling in missing years would introduce artificiality into the data
- It is better to analyse the actual observed data

**Why we dropped missing inflation years:**
- Only 2 years are missing (1981, 1982)
- The gaps are most likely due to limitations in early
- Minimal effect on overall analysis
- No need for imputation

**Why we used an inner join for merging:**
- This only includes years present in both datasets
- Guarantees a valid comparison between poverty and inflation measures
- Result: 7 shared years (1993, 2000, 2005, 2008, 2010, 2014, 2022)

### 7.4 Validating the Cleaned Poverty Dataset

In [20]:
print("Missing values:")
print(poverty_clean[["Year", "Poverty"]].isna().sum())

print("\nDuplicate rows:", poverty_clean.duplicated().sum())

print("\nYear range:")
print(
    int(poverty_clean["Year"].min()),
    "to",
    int(poverty_clean["Year"].max())
)

print("\nData types:")
print(poverty_clean[["Year", "Poverty"]].dtypes)

Missing values:
Year       0
Poverty    0
dtype: int64

Duplicate rows: 0

Year range:
1993 to 2022

Data types:
Year         int64
Poverty    float64
dtype: object

## Step 8: Reshaping the Inflation Dataset

### 8.1 Converting Wide Format to Long Format

In [21]:
inflation_year_columns = [
    col for col in inflation_actual.columns
    if str(col).isdigit() and 1900 <= int(col) <= 2025
]

print("Number of inflation year columns:", len(inflation_year_columns))
print("First years:", inflation_year_columns[:5])
print("Last years:", inflation_year_columns[-5:])

Number of inflation year columns: 46
First years: ['1980', '1981', '1982', '1983', '1984']
Last years: ['2021', '2022', '2023', '2024', '2025']

### 8.2 Converting Inflation Data to Long Format

In [22]:
inflation_long = inflation_actual.melt(
    id_vars=[
        "REF_AREA",
        "REF_AREA_LABEL",
        "INDICATOR",
        "INDICATOR_LABEL"
    ],
    value_vars=inflation_year_columns,
    var_name="Year",
    value_name="Inflation"
)

inflation_long["Year"] = pd.to_numeric(
    inflation_long["Year"],
    errors="coerce"
)

inflation_long["Inflation"] = pd.to_numeric(
    inflation_long["Inflation"],
    errors="coerce"
)

print("Inflation data reshaped successfully.")
display(inflation_long.head())

Inflation data reshaped successfully.

,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,Year,Inflation
0,ZAF,South Africa,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",1980,14.236
1,ZAF,South Africa,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",1981,15.348
2,ZAF,South Africa,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",1982,13.721
3,ZAF,South Africa,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",1983,12.797
4,ZAF,South Africa,IMF_WEO_PCPIPCH,"Inflation, average consumer prices, Percent ch...",1984,11.345

### 8.3 Checking Missing Inflation Observations

In [23]:
inflation_missing = inflation_long["Inflation"].isna().sum()
inflation_total = len(inflation_long)

print("Total inflation observations:", inflation_total)
print("Missing inflation observations:", inflation_missing)

print(
    "Missing percentage:",
    round((inflation_missing / inflation_total) * 100, 2),
    "%"
)

Total inflation observations: 46
Missing inflation observations: 2
Missing percentage: 4.35 %

### 8.4 Handling Missing Inflation Values

Missing inflation observations are removed only where the actual inflation value is unavailable. The missing values are not replaced with zero because zero inflation represents a valid economic observation, whereas a missing value represents unavailable data.

In [24]:
inflation_clean = inflation_long.dropna(
    subset=["Year", "Inflation"]
).copy()

print("Observations before cleaning:", len(inflation_long))
print("Observations after cleaning:", len(inflation_clean))
print(
    "Observations removed:",
    len(inflation_long) - len(inflation_clean)
)

Observations before cleaning: 46
Observations after cleaning: 44
Observations removed: 2

### 8.5 Validating the Cleaned Inflation Dataset

The cleaned inflation dataset is validated to confirm that missing analytical values have been addressed, duplicate records are absent, the year range is valid, and the Year and Inflation variables have appropriate data types.

In [25]:
print("Missing values:")
print(inflation_clean[["Year", "Inflation"]].isna().sum())

print("\nDuplicate rows:", inflation_clean.duplicated().sum())

print("\nYear range:")
print(
    int(inflation_clean["Year"].min()),
    "to",
    int(inflation_clean["Year"].max())
)

print("\nData types:")
print(inflation_clean[["Year", "Inflation"]].dtypes)

Missing values:
Year         0
Inflation    0
dtype: int64

Duplicate rows: 0

Year range:
1980 to 2023

Data types:
Year           int64
Inflation    float64
dtype: object

## Step 9: Preparing the Datasets for Integration

### 9.1 Comparing Year Coverage

In [26]:
print("POVERTY")
print("Minimum year:", int(poverty_clean["Year"].min()))
print("Maximum year:", int(poverty_clean["Year"].max()))
print("Valid observations:", len(poverty_clean))

print("\nINFLATION")
print("Minimum year:", int(inflation_clean["Year"].min()))
print("Maximum year:", int(inflation_clean["Year"].max()))
print("Valid observations:", len(inflation_clean))

POVERTY
Minimum year: 1993
Maximum year: 2022
Valid observations: 7

INFLATION
Minimum year: 1980
Maximum year: 2023
Valid observations: 44

### 9.2 Identifying Common Years

In [27]:
poverty_year_set = set(poverty_clean["Year"])
inflation_year_set = set(inflation_clean["Year"])

common_years = sorted(
    poverty_year_set.intersection(inflation_year_set)
)

print("Number of common years:", len(common_years))
print("Common year range:", min(common_years), "to", max(common_years))
print("\nCommon years:")
print(common_years)

Number of common years: 7
Common year range: 1993 to 2022

Common years:
[1993, 2000, 2005, 2008, 2010, 2014, 2022]

### 9.3 Checking for Unique Yearly Observations

Before combining the datasets, the number of observations per year is checked to ensure that each year has a single valid value. This prevents duplicated records from distorting the merged analysis.

In [28]:
print("POVERTY OBSERVATIONS PER YEAR")
print(poverty_clean["Year"].value_counts().sort_index())

print("\nINFLATION OBSERVATIONS PER YEAR")
print(inflation_clean["Year"].value_counts().sort_index())

POVERTY OBSERVATIONS PER YEAR
Year
1993    1
2000    1
2005    1
2008    1
2010    1
2014    1
2022    1
Name: count, dtype: int64

INFLATION OBSERVATIONS PER YEAR
Year
1980    1
1981    1
1982    1
1983    1
1984    1
1985    1
1986    1
1987    1
1988    1
1989    1
1990    1
1991    1
1992    1
1993    1
1994    1
1995    1
1996    1
1997    1
1998    1
1999    1
2000    1
2001    1
2002    1
2003    1
2004    1
2005    1
2006    1
2007    1
2008    1
2009    1
2010    1
2011    1
2012    1
2013    1
2014    1
2015    1
2016    1
2017    1
2018    1
2019    1
2020    1
2021    1
2022    1
2023    1
Name: count, dtype: int64

### 9.4 Aligning the Datasets to Common Years

The poverty and inflation datasets are aligned using their common years. This ensures that each observation in the final dataset represents the same year for both indicators.

In [29]:
poverty_common = poverty_clean[
    poverty_clean["Year"].isin(common_years)
].copy()

inflation_common = inflation_clean[
    inflation_clean["Year"].isin(common_years)
].copy()

print("Poverty observations for common years:", len(poverty_common))
print("Inflation observations for common years:", len(inflation_common))

Poverty observations for common years: 7
Inflation observations for common years: 7

## Step 10: Integrating the South African Datasets

### 10.1 Merging Poverty and Inflation by Year

The two cleaned South African datasets are merged using Year as the common identifier. An inner join is used so that only years with valid observations in both datasets are included in the integrated dataset.

In [30]:
combined_sa = pd.merge(
    poverty_common[
        ["Year", "Poverty"]
    ],
    inflation_common[
        ["Year", "Inflation"]
    ],
    on="Year",
    how="inner"
)

combined_sa = combined_sa.sort_values("Year").reset_index(drop=True)

print("Final combined dataset:")
display(combined_sa)

Final combined dataset:

   Year  Poverty  Inflation
0  1993     75.4      9.720
1  2000     78.5      5.322
2  2005     74.9      3.367
3  2008     70.5     11.020
4  2010     65.1      4.211
5  2014     65.7      6.104
6  2022     59.6      6.869

### 10.2 Validating the Integrated Dataset

The final integrated dataset is validated to ensure that all years are unique, no analytical values are missing, and the variables have appropriate data types. This confirms that the dataset is ready for statistical analysis.

In [31]:
print("FINAL DATASET VALIDATION")
print("=" * 40)

print("Number of observations:", len(combined_sa))
print("Number of duplicate rows:", combined_sa.duplicated().sum())

print("\nMissing values:")
print(combined_sa.isna().sum())

print("\nDuplicate years:", combined_sa["Year"].duplicated().sum())

print("\nData types:")
print(combined_sa.dtypes)

print("\nYear range:")
print(
    combined_sa["Year"].min(),
    "to",
    combined_sa["Year"].max()
)

FINAL DATASET VALIDATION
========================================
Number of observations: 7
Number of duplicate rows: 0

Missing values:
Year         0
Poverty      0
Inflation    0
dtype: int64

Duplicate years: 0

Data types:
Year           int64
Poverty      float64
Inflation    float64
dtype: object

Year range:
1993 to 2022

### 10.3 Final Clean Dataset

The resulting dataset contains South African poverty and inflation observations for the years in which both indicators are available. The data is ordered chronologically and is ready for descriptive statistical analysis.

In [32]:
display(combined_sa)

   Year  Poverty  Inflation
0  1993     75.4      9.720
1  2000     78.5      5.322
2  2005     74.9      3.367
3  2008     70.5     11.020
4  2010     65.1      4.211
5  2014     65.7      6.104
6  2022     59.6      6.869

## Step 11: Descriptive Statistical Analysis

### 11.1 Summary Statistics

In [33]:
descriptive_stats = combined_sa[
    ["Poverty", "Inflation"]
].describe().T

descriptive_stats

           count       mean       std     min      25%     50%      75%    max
Poverty      7.0  69.957143  6.786226  59.600  65.4000  70.500  75.1500  78.50
Inflation    7.0   6.659000  2.809440   3.367   4.7665   6.104   8.2945  11.02

### 11.2 Measuring Change Over the Analysis Period

The percentage-point change between the earliest and latest common observations is calculated for both indicators to provide an initial interpretation of the long-term movement in the South African data.

In [34]:
first_year = combined_sa.iloc[0]
last_year = combined_sa.iloc[-1]

poverty_change = last_year["Poverty"] - first_year["Poverty"]
inflation_change = last_year["Inflation"] - first_year["Inflation"]

print(f"Poverty change ({int(first_year['Year'])} to {int(last_year['Year'])}): "
      f"{poverty_change:.2f} percentage points")

print(f"Inflation change ({int(first_year['Year'])} to {int(last_year['Year'])}): "
      f"{inflation_change:.2f} percentage points")

Poverty change (1993 to 2022): -15.80 percentage points
Inflation change (1993 to 2022): -2.85 percentage points

### 11.3 Identifying Extreme Values

The highest and lowest observed values for poverty and inflation are identified to provide meaningful interpretation of the descriptive statistics.

In [35]:
poverty_max = combined_sa.loc[combined_sa["Poverty"].idxmax()]
poverty_min = combined_sa.loc[combined_sa["Poverty"].idxmin()]

inflation_max = combined_sa.loc[combined_sa["Inflation"].idxmax()]
inflation_min = combined_sa.loc[combined_sa["Inflation"].idxmin()]

print("POVERTY")
print(
    f"Highest: {poverty_max['Poverty']:.1f}% "
    f"in {int(poverty_max['Year'])}"
)
print(
    f"Lowest: {poverty_min['Poverty']:.1f}% "
    f"in {int(poverty_min['Year'])}"
)

print("\nINFLATION")
print(
    f"Highest: {inflation_max['Inflation']:.3f}% "
    f"in {int(inflation_max['Year'])}"
)
print(
    f"Lowest: {inflation_min['Inflation']:.3f}% "
    f"in {int(inflation_min['Year'])}"
)

POVERTY
Highest: 78.5% in 2000
Lowest: 59.6% in 2022

INFLATION
Highest: 11.020% in 2008
Lowest: 3.367% in 2005

### 11.4 Measuring Variability

The range and interquartile range (IQR) are calculated to assess the spread of poverty and inflation observations. The IQR represents the middle 50% of the observations and is less affected by extreme values.

In [36]:
for variable in ["Poverty", "Inflation"]:
    minimum = combined_sa[variable].min()
    maximum = combined_sa[variable].max()
    q1 = combined_sa[variable].quantile(0.25)
    q3 = combined_sa[variable].quantile(0.75)
    
    data_range = maximum - minimum
    iqr = q3 - q1

    print(variable)
    print(f"Range: {data_range:.3f}")
    print(f"IQR: {iqr:.3f}")
    print()

Poverty
Range: 18.900
IQR: 9.750

Inflation
Range: 7.653
IQR: 3.528

### 11.5 Consolidated Descriptive Statistics

A consolidated summary table is produced to present the main descriptive statistics for both indicators in a clear and comparable format.

In [37]:
summary_table = pd.DataFrame({
    "Indicator": ["Poverty", "Inflation"],
    "Mean": [
        combined_sa["Poverty"].mean(),
        combined_sa["Inflation"].mean()
    ],
    "Median": [
        combined_sa["Poverty"].median(),
        combined_sa["Inflation"].median()
    ],
    "Std Dev": [
        combined_sa["Poverty"].std(),
        combined_sa["Inflation"].std()
    ],
    "Minimum": [
        combined_sa["Poverty"].min(),
        combined_sa["Inflation"].min()
    ],
    "Maximum": [
        combined_sa["Poverty"].max(),
        combined_sa["Inflation"].max()
    ]
})

summary_table.round(3)

   Indicator    Mean  Median  Std Dev  Minimum  Maximum
0    Poverty  69.957  70.500    6.786   59.600    78.50
1  Inflation   6.659   6.104    2.809    3.367    11.02

### 11.6 Initial Statistical Insights

The descriptive statistics are interpreted to identify the central tendency, variability, and overall movement of poverty and inflation across the common South African observations.

In [38]:
print("KEY FINDINGS")
print("=" * 63)

print(
    f"Average poverty: "
    f"{combined_sa['Poverty'].mean():.2f}%"
)

print(
    f"Median poverty: "
    f"{combined_sa['Poverty'].median():.2f}%"
)

print(
    f"Average inflation: "
    f"{combined_sa['Inflation'].mean():.2f}%"
)

print(
    f"Median inflation: "
    f"{combined_sa['Inflation'].median():.2f}%"
)

print(
    f"Poverty decreased by "
    f"{abs(poverty_change):.2f} percentage points "
    f"from 1993 to 2022."
)

print(
    f"Inflation decreased by "
    f"{abs(inflation_change):.2f} percentage points "
    f"from 1993 to 2022."
)

KEY FINDINGS
===============================================================
Average poverty: 69.96%
Median poverty: 70.50%
Average inflation: 6.66%
Median inflation: 6.10%
Poverty decreased by 15.80 percentage points from 1993 to 2022.
Inflation decreased by 2.85 percentage points from 1993 to 2022.